global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgresql'
    static_configs:
      - targets: ['62.84.114.234:5432']  # IP и порт вашего контейнера PostgreSQL
    metrics_path: /metrics
    params:
      format: [prometheus]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 62.84.114.234:9187  # IP и порт, где работает экспортер pg_prometheus

